FROM node:22-bullseye

RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["sh", "-c", "npm install && npm run dev --workspace=app -- -p 3000"]
